### 
GET http://localhost:8080/api/maskghfhhgfdf HTTP/1.1

### bad body request

POST http://localhost:8080/api/mask HTTP/1.1
Content-Type: application/json 

{
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED"
  ],
  "cost": "ajkfdlffkajf",
  "isCustom": "ajf",
  "image": "image"
}

### bad path request

PUT http://localhost:8080/api/mask/adj HTTP/1.1
Content-Type: application/json

{
  "maskId": 5,
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED",
    "GREEN"
  ],
  "cost": 12.00,
  "isCustom": false,
  "image": "Updated_image"
}