### findAll
GET http://localhost:8080/api/mask HTTP/1.1

### should findById

GET http://localhost:8080/api/mask/1 HTTP/1.1

### should not findById

GET http://localhost:8080/api/mask/999 HTTP/1.1

### should add

POST http://localhost:8080/api/add HTTP/1.1
Content-Type: application/json 

{
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED"
  ],
  "cost": 5.00,
  "isCustom": false,
  "image": "image"
}

### should not add

POST http://localhost:8080/api/add HTTP/1.1
Content-Type: application/json 

{
  "maskId": 998,
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED"
  ],
  "cost": 5.00,
  "isCustom": false,
  "image": "image"
}

### should update

PUT http://localhost:8080/api/4 HTTP/1.1
Content-Type: application/json

{
  "maskId": 4,
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED",
    "GREEN"
  ],
  "cost": 12.00,
  "isCustom": false,
  "image": "Updated_image"
}

### should not update (conflict)

PUT http://localhost:8080/api/4 HTTP/1.1
Content-Type: application/json

{
  "maskId": 5,
  "material": "POLY_COT",
  "style": "ATHLETIC",
  "colors": [
    "RED",
    "GREEN"
  ],
  "cost": 12.00,
  "isCustom": false,
  "image": "Updated_image"
}

### should delete

DELETE http://localhost:8080/4 HTTP/1.1

### should not delete non existing

DELETE http://localhost:8080/997 HTTP/1.1


### should findByColor

GET http://localhost:8080/api/mask/color/red HTTP/1.1

### should findByStyle

GET http://localhost:8080/api/mask/style/athLETic HTTP/1.1

### should findByMaterial

GET http://localhost:8080/api/mask/material/COTTON HTTP/1.1